name = "konbanwa"
license = "MIT"
licenselink = "https://github.com/rdela/theme-konbanwa/blob/master/LICENSE.md"
description = "Konbanwa, Hello Friend's mellower cousin who is way into Micro.blog"
homepage = "https://github.com/rdela/theme-konbanwa/"
tags = ["blog", "clean", "customizable", "dark", "highlighting", "light", "minimal", "monochromatic", "multilingual", "personal", "responsive", "simple", "technical"]
features = ["blog", "shortcode", "syntax Highlighting"]
min_version = 0.30

[author]
  name = "rdela"
  homepage = "https://rdela.com"
  twitter = "https://twitter.com/rickydelaveaga"
